/**
 * /privacy/en — Privacy Policy (EN, draft).
 *
 * Straight translation of `/privacy` (UA). See PLAN.md WP3 for the choice
 * of a separate route over an i18n framework (avoiding a new dependency
 * pre soft-launch).
 */
import Link from "next/link";

export const metadata = {
  title: "Privacy Policy · hart.crimea.ua",
  description:
    "How the platform handles data: no tracking cookies, no mandatory sign-up, data hosted in Ukraine.",
};

interface Section {
  readonly id: string;
  readonly title: string;
  readonly body: string;
}

const SECTIONS: ReadonlyArray<Section> = [
  {
    id: "pii",
    title: "1. Minimum personal data",
    body:
      "We do not collect email addresses, IP addresses, or any personal identifiers in product telemetry. " +
      "Every event (export request, validation error, export completion) is recorded without a user identifier. " +
      "Instead, we use a `session_hash` pseudonym with a daily salt — a technical uniqueness metric that does " +
      "not allow us or third parties to track a specific person across days.",
  },
  {
    id: "cookies",
    title: "2. No tracking cookies",
    body:
      "Analytics is Umami self-hosted in our data centre (cookie-less: no tracking cookie is set, no external " +
      "service receives your browser fingerprint). No GDPR consent banner is required. Technical cookies " +
      "(auth session, CSRF token) will appear later when we add sign-up (Roadmap Phase 3).",
  },
  {
    id: "sentry",
    title: "3. Technical error reports",
    body:
      "When something breaks in the browser or server, we send a technical report to Sentry (SaaS). Before " +
      "sending, a `beforeSend` filter strips email, IP, cookies, and any potentially sensitive headers. Only a " +
      "stack trace and technical context remain in the report — no personal data.",
  },
  {
    id: "location",
    title: "4. Where application data lives",
    body:
      "Database, cache, job queue, and generated drawings — all on a single server in the Mirohost data centre " +
      "in Kyiv, Ukraine. We deliberately chose a Ukrainian hosting provider for data sovereignty (ADR-011).",
  },
  {
    id: "backups",
    title: "5. Encrypted backups in Cloudflare R2",
    body:
      "Daily database backups (03:00 Kyiv time) are locally encrypted (age-encryption) before being uploaded " +
      "to Cloudflare R2 (S3-compatible object storage). Cloudflare is outside Ukraine, but data in R2 is " +
      "unreadable without our private key, which is stored separately from the vault.",
  },
  {
    id: "donations",
    title: "6. Donations go directly to Ukrainian Armed Forces funds",
    body:
      "The platform is non-profit and does NOT accept any funds. The «Support Armed Forces» buttons link " +
      "directly to Monobank Banka or UNITED24 — official fundraisers with transparent accounting. We are only " +
      "a link intermediary; no transaction passes through our bank account (we do not have one).",
  },
  {
    id: "drawings",
    title: "7. Drawings are advisory",
    body:
      "The DXF/PDF/STEP files generated by the platform are a starting point for a manufacturing order, not a " +
      "finished engineering document. Before manufacturing, a human who understands material, bending, and the " +
      "specifics of the particular machine must verify the drawing. We are not liable for defects caused by a " +
      "mismatch between generated parameters and the real production process.",
  },
  {
    id: "uptime",
    title: "8. Best-effort uptime, no SLA",
    body:
      "This is a social project running on a single server (2 vCPU / 4 GB) without failover. We try to keep " +
      "the platform available around the clock, but provide no guarantee regarding response time, uptime, data " +
      "integrity, or long-term storage durability. If your process requires an SLA, use local CAD software or " +
      "order from an industrial contractor.",
  },
];

export default function PrivacyPageEn() {
  return (
    <div className="bg-bg mx-auto flex w-full max-w-3xl flex-col gap-8 px-4 py-10 md:py-16">
      <div
        data-testid="privacy-draft-banner"
        className="border-warning bg-warning-surface rounded-lg border-2 p-4"
      >
        <p className="text-warning-foreground text-sm font-semibold">
          Draft. Not legal advice; the final version follows a lawyer review (Roadmap 5.4).
        </p>
      </div>

      <header data-testid="privacy-hero" className="flex flex-col gap-3">
        <h1 className="text-fg text-3xl font-bold md:text-4xl">Privacy Policy</h1>
        <p className="text-fg-muted">
          How this platform handles your data — written from the actual state of the code, not from
          an abstract template. Українська:{" "}
          <Link href="/privacy" className="underline">
            /privacy
          </Link>
          .
        </p>
      </header>

      <div className="flex flex-col gap-6">
        {SECTIONS.map((section) => (
          <section
            key={section.id}
            id={section.id}
            data-testid={`privacy-section-${section.id}`}
            className="flex flex-col gap-2"
          >
            <h2 className="text-fg text-xl font-semibold">{section.title}</h2>
            <p className="text-fg-muted leading-relaxed">{section.body}</p>
          </section>
        ))}
      </div>

      <footer className="border-border border-t pt-6">
        <p className="text-fg-subtle text-sm">
          Last updated: 2026-07-12. Questions —{" "}
          <a
            href="mailto:feedback@hart.crimea.ua"
            className="underline"
            data-testid="privacy-contact-email"
          >
            feedback@hart.crimea.ua
          </a>
          .
        </p>
      </footer>
    </div>
  );
}
